version: '3.1'
services:
  cms:
    build:
      context: ./app
      dockerfile: Dockerfile.dev
    ports:
      - '80:80'
    depends_on:
      - mongodb
    environment:
      - mode=local
      - TZ=Asia/Hong_Kong
      - cdn_version=1.18
      - DB_PREFIX=mongodb
      - DB_HOST=mongodb
      - DB_USER=root
      - DB_PASSWORD=123456
      - DB_NAME=db
      - DB_PORT=27017
      - PORT=80
    restart: always
    volumes:
      - ./app:/usr/src/app
      - ./app/node_modules:/usr/src/app/node_modules
  cms-frontend:
    build:
      context: ./frontend
    ports:
      - '3000:3000'
    environment:
      - PORT=3000
    restart: always
    volumes:
      - ./frontend:/usr/src/frontend
      - ./frontend/node_modules:/usr/src/frontend/node_modules
    depends_on:
      - cms
  mongodb:
    image: mongo:5.0.2
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=123456
    ports:
      - "27017:27017"
    volumes:
      - db:/usr/src/db

volumes:
  db: